# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Belgrade"
    ignore:
      - dependency-name: "*quasar*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint-webpack-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "chalk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "inquirer"
        update-types: ["version-update:semver-major"]